const $=id=>document.getElementById(id);
const A={
lo:{viewSite:'ເບິ່ງໜ້າເວັບ',adminLogin:'ເຂົ້າລະບົບ Admin',password:'ລະຫັດຜ່ານ',login:'ເຂົ້າລະບົບ',introTitle:'ຈັດການລູກຄ້າ, ລາຄາ ແລະ ຜົນງານ',introText:'ຮັບຄຳຂໍໃບສະເໜີລາຄາ, ຕິດຕາມສະຖານະລູກຄ້າ, ປ່ຽນລາຄາ ແລະ ຈັດການຜົນງານ.',note:'ໝາຍເຫດ:',noteText:'ຂໍ້ມູນຈະບັນທຶກໃນ Supabase ແລະ ອັບເດດໃຫ້ຜູ້ເຂົ້າຊົມທຸກຄົນເຫັນ.',crmTitle:'ລາຍການລູກຄ້າຂໍໃບສະເໜີລາຄາ',refresh:'ອັບເດດລາຍການ',search:'ຄົ້ນຫາ',searchPlaceholder:'ຊື່, ເບີໂທ, ທຸລະກິດ',status:'ສະຖານະ',all:'ທັງໝົດ',pricingTitle:'ຈັດການລາຄາແພັກເກດ',currency:'ສະກຸນເງິນ',savePrice:'ບັນທຶກລາຄາ',addProject:'ເພີ່ມຜົນງານ',editProject:'ແກ້ໄຂຜົນງານ',coverImage:'ຮູບໜ້າປົກ',imageHelp:'ແນະນຳຮູບແນວນອນ 1600 × 900 px. ຖ້າບໍ່ເລືອກຮູບໃໝ່ ຈະໃຊ້ຮູບເກົ່າ.',saveProject:'ບັນທຶກຜົນງານ',cancel:'ຍົກເລີກ',currentProjects:'ຜົນງານປັດຈຸບັນ',logout:'ອອກຈາກລະບົບ',totalCustomers:'ລູກຄ້າທັງໝົດ',noCustomers:'ບໍ່ພົບລາຍການລູກຄ້າ',noBusiness:'ບໍ່ໄດ້ລະບຸຊື່ທຸລະກິດ',delete:'ລຶບ',edit:'ແກ້ໄຂ',noProjects:'ຍັງບໍ່ມີຜົນງານ',loginWorking:'ກຳລັງເຂົ້າລະບົບ…',loginDone:'ເຂົ້າລະບົບແລ້ວ',saving:'ກຳລັງບັນທຶກ…',savedProject:'ບັນທຶກຜົນງານແລ້ວ',savedPrice:'ບັນທຶກລາຄາແລ້ວ',deletedProject:'ລຶບຜົນງານແລ້ວ',confirmProject:'ຕ້ອງການລຶບຜົນງານນີ້ບໍ?',maxProjects:'ເພີ່ມໄດ້ສູງສຸດ 6 ຜົນງານ',updatedLead:'ອັບເດດສະຖານະລູກຄ້າແລ້ວ',confirmLead:'ຕ້ອງການລຶບຂໍ້ມູນລູກຄ້ານີ້ບໍ?',deletedLead:'ລຶບຂໍ້ມູນລູກຄ້າແລ້ວ',noExport:'ຍັງບໍ່ມີຂໍ້ມູນລູກຄ້າສຳລັບ Export',exported:'Export ລາຍຊື່ລູກຄ້າເປັນ CSV ແລ້ວ',config:'ກະລຸນາໃສ່ Supabase URL ແລະ anon key ໃນ supabase-config.js',missingLeads:'ບໍ່ພົບຕາຕະລາງ leads — ກະລຸນາຮັນ supabase-setup-v2.2.sql ໃນ Supabase SQL Editor'},
th:{viewSite:'ดูหน้าเว็บไซต์',adminLogin:'เข้าสู่ระบบ Admin',password:'รหัสผ่าน',login:'เข้าสู่ระบบ',introTitle:'จัดการลูกค้า ราคา และผลงาน',introText:'รับคำขอใบเสนอราคา ติดตามสถานะลูกค้า เปลี่ยนราคา และจัดการผลงาน',note:'หมายเหตุ:',noteText:'ข้อมูลจะบันทึกใน Supabase และอัปเดตให้ผู้เข้าชมทุกคนเห็น',crmTitle:'รายการลูกค้าขอใบเสนอราคา',refresh:'อัปเดตรายการ',search:'ค้นหา',searchPlaceholder:'ชื่อ, เบอร์โทร, ธุรกิจ',status:'สถานะ',all:'ทั้งหมด',pricingTitle:'จัดการราคาแพ็กเกจ',currency:'สกุลเงิน',savePrice:'บันทึกราคา',addProject:'เพิ่มผลงาน',editProject:'แก้ไขผลงาน',coverImage:'รูปหน้าปก',imageHelp:'แนะนำรูปแนวนอน 1600 × 900 px หากไม่เลือกรูปใหม่ ระบบจะใช้รูปเดิม',saveProject:'บันทึกผลงาน',cancel:'ยกเลิก',currentProjects:'ผลงานปัจจุบัน',logout:'ออกจากระบบ',totalCustomers:'ลูกค้าทั้งหมด',noCustomers:'ไม่พบรายการลูกค้า',noBusiness:'ไม่ระบุชื่อธุรกิจ',delete:'ลบ',edit:'แก้ไข',noProjects:'ยังไม่มีผลงาน',loginWorking:'กำลังเข้าสู่ระบบ…',loginDone:'เข้าสู่ระบบแล้ว',saving:'กำลังบันทึก…',savedProject:'บันทึกผลงานแล้ว',savedPrice:'บันทึกราคาแล้ว',deletedProject:'ลบผลงานแล้ว',confirmProject:'ต้องการลบผลงานนี้หรือไม่?',maxProjects:'เพิ่มได้สูงสุด 6 ผลงาน',updatedLead:'อัปเดตสถานะลูกค้าแล้ว',confirmLead:'ต้องการลบข้อมูลลูกค้านี้หรือไม่?',deletedLead:'ลบข้อมูลลูกค้าแล้ว',noExport:'ยังไม่มีข้อมูลลูกค้าสำหรับ Export',exported:'Export รายชื่อลูกค้าเป็น CSV แล้ว',config:'กรุณาใส่ Supabase URL และ anon key ใน supabase-config.js',missingLeads:'ไม่พบตาราง leads — กรุณารัน supabase-setup-v2.2.sql ใน Supabase SQL Editor'},
en:{viewSite:'View website',adminLogin:'Admin Login',password:'Password',login:'Log in',introTitle:'Manage customers, pricing and portfolio',introText:'Receive quote requests, track customer status, update prices and manage portfolio projects.',note:'Note:',noteText:'Data is stored in Supabase and updates are shown to website visitors.',crmTitle:'Customer quote requests',refresh:'Refresh list',search:'Search',searchPlaceholder:'Name, phone, business',status:'Status',all:'All',pricingTitle:'Manage package pricing',currency:'Currency',savePrice:'Save pricing',addProject:'Add project',editProject:'Edit project',coverImage:'Cover image',imageHelp:'Recommended landscape image: 1600 × 900 px. Leave empty when editing to keep the current image.',saveProject:'Save project',cancel:'Cancel',currentProjects:'Current projects',logout:'Log out',totalCustomers:'Total customers',noCustomers:'No customer records found',noBusiness:'Business name not provided',delete:'Delete',edit:'Edit',noProjects:'No projects yet',loginWorking:'Logging in…',loginDone:'Logged in',saving:'Saving…',savedProject:'Project saved',savedPrice:'Pricing saved',deletedProject:'Project deleted',confirmProject:'Delete this project?',maxProjects:'A maximum of 6 projects is allowed',updatedLead:'Customer status updated',confirmLead:'Delete this customer record?',deletedLead:'Customer record deleted',noExport:'No customer data available for export',exported:'Customer list exported as CSV',config:'Add your Supabase URL and anon key in supabase-config.js',missingLeads:'The leads table was not found — run supabase-setup-v2.2.sql in Supabase SQL Editor'}
};
let lang=localStorage.getItem('lws-lang')||'lo';
const t=k=>A[lang]?.[k]||A.lo[k]||k;
function applyLang(l){lang=l;localStorage.setItem('lws-lang',l);document.documentElement.lang=l;document.querySelectorAll('[data-ai]').forEach(el=>el.textContent=t(el.dataset.ai));document.querySelectorAll('[data-ai-placeholder]').forEach(el=>el.placeholder=t(el.dataset.aiPlaceholder));if($('admin-lang'))$('admin-lang').value=l;if($('admin-app')&&!$('admin-app').hidden){render();renderLeadStats(cachedLeads);paintLeads();}}
$('admin-lang').addEventListener('change',e=>applyLang(e.target.value));applyLang(lang);
const form=$('project-form'),list=$('project-list'),count=$('count'),cancel=$('cancel-edit');let currentImage='',cachedLeads=[];
const show=(msg,type='ok')=>{const el=$('global-status');el.textContent=msg;el.dataset.type=type;};
async function requireLogin(){if(!window.lwsSupabase){$('admin-app').hidden=true;$('login-card').hidden=false;show(t('config'),'error');return false;}const {data}=await window.lwsSupabase.auth.getSession();const logged=Boolean(data.session);$('login-card').hidden=logged;$('admin-app').hidden=!logged;return logged;}
$('login-form').addEventListener('submit',async e=>{e.preventDefault();show(t('loginWorking'));const {error}=await window.lwsSupabase.auth.signInWithPassword({email:$('login-email').value,password:$('login-password').value});if(error)return show(error.message,'error');await requireLogin();await boot();show(t('loginDone'));});
$('logout').addEventListener('click',async()=>{await window.lwsSupabase.auth.signOut();location.reload();});
async function uploadImage(file){if(!file)return currentImage||'assets/portfolio.jpg';const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`projects/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await window.lwsSupabase.storage.from('portfolio').upload(path,file,{upsert:false,cacheControl:'3600'});if(error)throw error;return window.lwsSupabase.storage.from('portfolio').getPublicUrl(path).data.publicUrl;}
async function render(){const projects=await getProjects();count.textContent=`(${projects.length}/6)`;list.innerHTML=projects.length?projects.map(p=>`<article class="admin-item"><img src="${p.image}" alt=""><div><h3>${p.name[lang]||p.name.lo||p.name.th||p.name.en}</h3><p>${p.url}</p><div class="item-actions"><button class="text-btn" data-edit="${p.id}">${t('edit')}</button><button class="text-btn danger" data-delete="${p.id}">${t('delete')}</button></div></div></article>`).join(''):`<div class="empty-admin">${t('noProjects')}</div>`;form.querySelector('button[type="submit"]').disabled=projects.length>=6&&!$('edit-id').value;return projects;}
function resetForm(){form.reset();$('edit-id').value='';currentImage='';$('form-title').textContent=t('addProject');cancel.hidden=true;render();}
form.addEventListener('submit',async e=>{e.preventDefault();try{const projects=await getProjects(),editId=$('edit-id').value;if(!editId&&projects.length>=6)throw new Error(t('maxProjects'));show(t('saving'));const image=await uploadImage($('project-image').files[0]);await saveProject({id:editId||crypto.randomUUID(),category:{lo:$('category-lo').value,th:$('category-th').value,en:$('category-en').value},name:{lo:$('name-lo').value,th:$('name-th').value,en:$('name-en').value},description:{lo:$('desc-lo').value,th:$('desc-th').value,en:$('desc-en').value},url:$('project-url').value,image,sort_order:editId?(projects.find(p=>p.id===editId)?.sort_order||0):projects.length});resetForm();show(t('savedProject'));}catch(err){show(err.message,'error');}});
list.addEventListener('click',async e=>{const edit=e.target.dataset.edit,del=e.target.dataset.delete,projects=await getProjects();if(del){if(confirm(t('confirmProject'))){try{await deleteProject(del);await render();show(t('deletedProject'));}catch(err){show(err.message,'error');}}return;}if(edit){const p=projects.find(x=>x.id===edit);if(!p)return;$('edit-id').value=p.id;currentImage=p.image;for(const k of ['lo','th','en']){$(`category-${k}`).value=p.category[k]||'';$(`name-${k}`).value=p.name[k]||'';$(`desc-${k}`).value=p.description[k]||'';}$('project-url').value=p.url||'';$('form-title').textContent=t('editProject');cancel.hidden=false;scrollTo({top:0,behavior:'smooth'});render();}});
cancel.addEventListener('click',resetForm);
$('pricing-form').addEventListener('submit',async e=>{e.preventDefault();try{const currency=$('price-currency').value.trim()||'ກີບ';await savePricing({starter:{price:$('price-starter').value.trim(),currency},business:{price:$('price-business').value.trim(),currency},premium:{price:$('price-premium').value.trim(),currency}});show(t('savedPrice'));}catch(err){show(err.message,'error');}});
async function loadPricingForm(){const d=await getPricing();$('price-starter').value=d.starter.price;$('price-business').value=d.business.price;$('price-premium').value=d.premium.price;$('price-currency').value=d.starter.currency||'ກີບ';}
function formatLeadDate(value){try{return new Intl.DateTimeFormat(lang==='lo'?'lo-LA':lang==='th'?'th-TH':'en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));}catch{return value||'';}}
function leadSafe(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function renderLeadStats(leads){const counts={new:0,contacted:0,completed:0};leads.forEach(x=>counts[x.status]=(counts[x.status]||0)+1);$('lead-stats').innerHTML=`<div><b>${leads.length}</b><span>${t('totalCustomers')}</span></div><div><b>${counts.new}</b><span>New</span></div><div><b>${counts.contacted}</b><span>Contacted</span></div><div><b>${counts.completed}</b><span>Completed</span></div>`;}
function paintLeads(){const q=($('lead-search')?.value||'').toLowerCase().trim(),filter=$('lead-filter')?.value||'all';const rows=cachedLeads.filter(x=>(filter==='all'||x.status===filter)&&[x.name,x.phone,x.email,x.business_name,x.message].join(' ').toLowerCase().includes(q));$('lead-list').innerHTML=rows.length?rows.map(x=>`<article class="lead-item" data-id="${leadSafe(x.id)}"><div class="lead-top"><div><span class="status-pill status-${leadSafe(x.status)}">${x.status[0].toUpperCase()+x.status.slice(1)}</span><h3>${leadSafe(x.name)}</h3><p>${leadSafe(x.business_name||t('noBusiness'))}</p></div><time>${leadSafe(formatLeadDate(x.created_at))}</time></div><div class="lead-meta"><a href="tel:${leadSafe(x.phone)}">☎ ${leadSafe(x.phone)}</a>${x.email?`<a href="mailto:${leadSafe(x.email)}">✉ ${leadSafe(x.email)}</a>`:''}<span>Service: ${leadSafe(x.service)}</span><span>Budget: ${leadSafe(x.budget||'-')}</span><span>Contact: ${leadSafe(x.preferred_contact||'-')}</span></div><div class="lead-message">${leadSafe(x.message)}</div><div class="lead-actions"><select data-status="${leadSafe(x.id)}"><option value="new" ${x.status==='new'?'selected':''}>New</option><option value="contacted" ${x.status==='contacted'?'selected':''}>Contacted</option><option value="completed" ${x.status==='completed'?'selected':''}>Completed</option></select><a class="btn btn-secondary small" href="https://wa.me/${leadSafe((x.phone||'').replace(/\D/g,''))}" target="_blank" rel="noopener">WhatsApp</a><button class="text-btn danger" data-delete-lead="${leadSafe(x.id)}" type="button">${t('delete')}</button></div></article>`).join(''):`<div class="empty-admin">${t('noCustomers')}</div>`;}
async function renderLeads(){try{cachedLeads=await getLeads();renderLeadStats(cachedLeads);paintLeads();}catch(err){const msg=String(err?.message||err);show(msg.includes('leads')?t('missingLeads'):msg,'error');}}
$('lead-search')?.addEventListener('input',paintLeads);$('lead-filter')?.addEventListener('change',paintLeads);$('refresh-leads')?.addEventListener('click',renderLeads);
$('lead-list')?.addEventListener('change',async e=>{const id=e.target.dataset.status;if(!id)return;try{await updateLeadStatus(id,e.target.value);const row=cachedLeads.find(x=>x.id===id);if(row)row.status=e.target.value;renderLeadStats(cachedLeads);paintLeads();show(t('updatedLead'));}catch(err){show(err.message,'error');}});
$('lead-list')?.addEventListener('click',async e=>{const id=e.target.dataset.deleteLead;if(!id||!confirm(t('confirmLead')))return;try{await deleteLead(id);cachedLeads=cachedLeads.filter(x=>x.id!==id);renderLeadStats(cachedLeads);paintLeads();show(t('deletedLead'));}catch(err){show(err.message,'error');}});
function csvCell(value){return `"${String(value??'').replaceAll('"','""')}"`;}
$('export-leads')?.addEventListener('click',()=>{if(!cachedLeads.length)return show(t('noExport'),'error');const headers=['created_at','name','phone','email','business_name','service','budget','preferred_contact','status','message'];const rows=[headers.join(','),...cachedLeads.map(lead=>headers.map(key=>csvCell(lead[key])).join(','))];const blob=new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`lao-web-studio-leads-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);show(t('exported'));});
async function boot(){await Promise.all([render(),loadPricingForm(),renderLeads()]);}
(async()=>{if(await requireLogin())await boot();})();
