const V24_STATUSES=['new','contacted','quotation_sent','in_progress','waiting','completed','cancelled'];
const V24_I18N={
 lo:{dash:'ພາບລວມທຸລະກິດ',team:'ທີມງານ',quotes:'ໃບສະເໜີລາຄາ',owner:'ຜູ້ຮັບຜິດຊອບ',priority:'ຄວາມສຳຄັນ',follow:'ວັນຕິດຕາມ',note:'ໝາຍເຫດ',save:'ບັນທຶກ CRM',createQuote:'ສ້າງໃບສະເໜີລາຄາ',amount:'ມູນຄ່າ',valid:'ໃຊ້ໄດ້ຮອດ',print:'ພິມ / PDF',email:'Email',month:'ລູກຄ້າໃໝ່ເດືອນນີ້',active:'ວຽກທີ່ກຳລັງດຳເນີນ',done:'ວຽກສຳເລັດ',value:'ມູນຄ່າໃບສະເໜີລາຄາ'},
 th:{dash:'ภาพรวมธุรกิจ',team:'ทีมงาน',quotes:'ใบเสนอราคา',owner:'ผู้รับผิดชอบ',priority:'ความสำคัญ',follow:'วันติดตาม',note:'หมายเหตุ',save:'บันทึก CRM',createQuote:'สร้างใบเสนอราคา',amount:'มูลค่า',valid:'ใช้ได้ถึง',print:'พิมพ์ / PDF',email:'อีเมล',month:'ลูกค้าใหม่เดือนนี้',active:'งานที่กำลังดำเนินการ',done:'งานเสร็จแล้ว',value:'มูลค่าใบเสนอราคา'},
 en:{dash:'Business overview',team:'Team',quotes:'Quotations',owner:'Owner',priority:'Priority',follow:'Follow-up date',note:'Notes',save:'Save CRM',createQuote:'Create quotation',amount:'Amount',valid:'Valid until',print:'Print / PDF',email:'Email',month:'New leads this month',active:'Active work',done:'Completed work',value:'Quotation value'}
};
let v24Employees=[],v24Quotes=[];
const v24t=k=>(V24_I18N[window.lang||'lo']||V24_I18N.lo)[k]||k;
async function v24LoadEmployees(){const {data,error}=await lwsSupabase.from('employees').select('*').eq('active',true).order('created_at');if(error)throw error;v24Employees=data||[];return v24Employees;}
async function v24LoadQuotes(){const {data,error}=await lwsSupabase.from('quotations').select('*').order('created_at',{ascending:false});if(error)throw error;v24Quotes=data||[];return v24Quotes;}
function v24Money(v){return new Intl.NumberFormat('lo-LA').format(Number(v||0))+' ກີບ';}
function v24PaintDashboard(){const leads=window.cachedLeads||[];const now=new Date(),month=leads.filter(x=>{const d=new Date(x.created_at);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}).length;const active=leads.filter(x=>['contacted','quotation_sent','in_progress','waiting'].includes(x.status)).length;const done=leads.filter(x=>x.status==='completed').length;const value=v24Quotes.filter(x=>x.status!=='cancelled').reduce((s,x)=>s+Number(x.amount||0),0);document.getElementById('v24-dashboard').innerHTML=[['month',month],['active',active],['done',done],['value',v24Money(value)]].map(([k,v])=>`<div><span>${v24t(k)}</span><b>${v}</b></div>`).join('');}
function v24OwnerOptions(selected){return v24Employees.map(e=>`<option value="${e.id}" ${e.id===selected?'selected':''}>${e.name}</option>`).join('');}
function v24EnhanceLeadCards(){document.querySelectorAll('.lead-item').forEach(card=>{if(card.querySelector('.v24-crm-fields'))return;const id=card.dataset.id,lead=(window.cachedLeads||[]).find(x=>String(x.id)===String(id));if(!lead)return;const actions=card.querySelector('.lead-actions');if(actions){const status=actions.querySelector('select');if(status){status.innerHTML=V24_STATUSES.map(s=>`<option value="${s}" ${lead.status===s?'selected':''}>${s.replaceAll('_',' ')}</option>`).join('');}}
const box=document.createElement('div');box.className='v24-crm-fields';box.innerHTML=`<label>${v24t('owner')}<select data-v24-owner>${v24OwnerOptions(lead.owner_id)}</select></label><label>${v24t('priority')}<select data-v24-priority><option value="low" ${lead.priority==='low'?'selected':''}>Low</option><option value="medium" ${!lead.priority||lead.priority==='medium'?'selected':''}>Medium</option><option value="high" ${lead.priority==='high'?'selected':''}>High</option></select></label><label>${v24t('follow')}<input type="date" data-v24-follow value="${lead.next_follow_up||''}"></label><label class="wide">${v24t('note')}<textarea rows="2" data-v24-note>${lead.admin_note||''}</textarea></label><button class="btn btn-primary small" data-v24-save="${id}">${v24t('save')}</button><button class="btn btn-secondary small" data-v24-quote="${id}">${v24t('createQuote')}</button>${lead.email?`<a class="btn btn-secondary small" href="mailto:${lead.email}">${v24t('email')}</a>`:''}`;card.appendChild(box);});v24PaintDashboard();}
async function v24SaveLead(card,id){const payload={owner_id:card.querySelector('[data-v24-owner]').value||null,priority:card.querySelector('[data-v24-priority]').value,next_follow_up:card.querySelector('[data-v24-follow]').value||null,admin_note:card.querySelector('[data-v24-note]').value||null};const {error}=await lwsSupabase.from('leads').update(payload).eq('id',id);if(error)throw error;show(v24t('save'));}
async function v24CreateQuote(id){const lead=(window.cachedLeads||[]).find(x=>String(x.id)===String(id));if(!lead)return;const amount=prompt(`${v24t('amount')} (ກີບ)`,lead.budget||'500000');if(amount===null)return;const valid=prompt(v24t('valid'),new Date(Date.now()+14*864e5).toISOString().slice(0,10));if(valid===null)return;const year=new Date().getFullYear();const {count}=await lwsSupabase.from('quotations').select('*',{count:'exact',head:true});const quote_no=`LWS-${year}-${String((count||0)+1).padStart(4,'0')}`;const {error}=await lwsSupabase.from('quotations').insert({quote_no,lead_id:id,customer_name:lead.name||lead.full_name,customer_email:lead.email,service:lead.service,amount:Number(String(amount).replace(/\D/g,''))||0,currency:'ກີບ',valid_until:valid,status:'draft',created_by:'Nutthaphon'});if(error)throw error;await lwsSupabase.from('leads').update({status:'quotation_sent'}).eq('id',id);show(`${quote_no} ✓`);await v24LoadQuotes();v24PaintQuotes();}
function v24PaintQuotes(){const el=document.getElementById('v24-quotes');el.innerHTML=v24Quotes.length?v24Quotes.map(q=>`<article><div><b>${q.quote_no}</b><span>${q.customer_name}</span></div><div><strong>${v24Money(q.amount)}</strong><small>${q.valid_until||''}</small></div><button class="text-btn" data-v24-print="${q.id}">${v24t('print')}</button></article>`).join(''):'<p class="empty-admin">—</p>';}
function v24PrintQuote(id){const q=v24Quotes.find(x=>String(x.id)===String(id));if(!q)return;const w=open('','_blank');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${q.quote_no}</title><style>body{font-family:Arial;padding:50px;color:#18233a}header{border-bottom:3px solid #c8a44d;padding-bottom:20px}h1{color:#0b2f78}.row{display:flex;justify-content:space-between;margin:22px 0}.total{font-size:28px;font-weight:bold;border-top:1px solid #ddd;padding-top:20px}</style></head><body><header><h1>LAO WEB STUDIO</h1><p>Quotation / ໃບສະເໜີລາຄາ</p></header><div class="row"><b>${q.quote_no}</b><span>${new Date(q.created_at).toLocaleDateString()}</span></div><h2>${q.customer_name}</h2><p>${q.customer_email||''}</p><div class="row"><span>${q.service}</span><strong>${v24Money(q.amount)}</strong></div><p>Valid until: ${q.valid_until||'-'}</p><div class="total">Total: ${v24Money(q.amount)}</div><script>print()<\/script></body></html>`);w.document.close();}
document.addEventListener('click',async e=>{try{const save=e.target.dataset.v24Save,quote=e.target.dataset.v24Quote,print=e.target.dataset.v24Print;if(save)await v24SaveLead(e.target.closest('.lead-item'),save);if(quote)await v24CreateQuote(quote);if(print)v24PrintQuote(print);}catch(err){show(err.message,'error');}});
const v24Observer=new MutationObserver(()=>v24EnhanceLeadCards());
async function v24Boot(){try{await Promise.all([v24LoadEmployees(),v24LoadQuotes()]);v24PaintQuotes();v24EnhanceLeadCards();v24Observer.observe(document.getElementById('lead-list'),{childList:true});}catch(err){console.warn('V2.4 migration required:',err.message);}}
window.addEventListener('load',()=>setTimeout(v24Boot,500));
