const V251_I18N={
 lo:{appointments:'ການນັດໝາຍລູກຄ້າ',addAppointment:'+ ເພີ່ມນັດໝາຍ',team:'ທີມງານ',files:'ໄຟລ໌ລູກຄ້າ',upload:'ອັບໂຫຼດໄຟລ໌',noAppointments:'ຍັງບໍ່ມີການນັດໝາຍ',upcoming:'ນັດໝາຍທີ່ກຳລັງມາ',staff:'ພະນັກງານ',modalTitle:'ເພີ່ມນັດໝາຍ',editTitle:'ແກ້ໄຂນັດໝາຍ',title:'ຫົວຂໍ້ນັດໝາຍ',lead:'ລູກຄ້າ',date:'ວັນ ແລະ ເວລາ',channel:'ຊ່ອງທາງ',location:'ສະຖານທີ່ / ລິ້ງປະຊຸມ',note:'ໝາຍເຫດ',cancel:'ຍົກເລີກ',save:'ບັນທຶກນັດໝາຍ',saved:'ບັນທຶກນັດໝາຍແລ້ວ ✓',scheduled:'ນັດແລ້ວ',completed:'ສຳເລັດ',cancelled:'ຍົກເລີກ',edit:'ແກ້ໄຂ',sun:'ອາ',mon:'ຈ',tue:'ອ',wed:'ພ',thu:'ພຫ',fri:'ສ',sat:'ສອ'},
 th:{appointments:'นัดหมายลูกค้า',addAppointment:'+ เพิ่มนัดหมาย',team:'ทีมงาน',files:'ไฟล์ลูกค้า',upload:'อัปโหลดไฟล์',noAppointments:'ยังไม่มีนัดหมาย',upcoming:'นัดหมายที่กำลังมาถึง',staff:'พนักงาน',modalTitle:'เพิ่มนัดหมาย',editTitle:'แก้ไขนัดหมาย',title:'หัวข้อนัดหมาย',lead:'ลูกค้า',date:'วันและเวลา',channel:'ช่องทาง',location:'สถานที่ / ลิงก์ประชุม',note:'หมายเหตุ',cancel:'ยกเลิก',save:'บันทึกนัดหมาย',saved:'บันทึกนัดหมายแล้ว ✓',scheduled:'นัดแล้ว',completed:'เสร็จแล้ว',cancelled:'ยกเลิก',edit:'แก้ไข',sun:'อา.',mon:'จ.',tue:'อ.',wed:'พ.',thu:'พฤ.',fri:'ศ.',sat:'ส.'},
 en:{appointments:'Customer appointments',addAppointment:'+ Add appointment',team:'Team',files:'Client files',upload:'Upload file',noAppointments:'No appointments yet',upcoming:'Upcoming appointments',staff:'Employees',modalTitle:'Add appointment',editTitle:'Edit appointment',title:'Appointment title',lead:'Customer',date:'Date and time',channel:'Channel',location:'Location / meeting link',note:'Note',cancel:'Cancel',save:'Save appointment',saved:'Appointment saved ✓',scheduled:'Scheduled',completed:'Completed',cancelled:'Cancelled',edit:'Edit',sun:'Sun',mon:'Mon',tue:'Tue',wed:'Wed',thu:'Thu',fri:'Fri',sat:'Sat'}
};
const v251t=k=>(V251_I18N[window.lang||'lo']||V251_I18N.lo)[k]||k;
let v25Appointments=[],v25Files=[],v25Team=[],v251Month=new Date(new Date().getFullYear(),new Date().getMonth(),1);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const localInputValue=d=>{const x=new Date(d),off=x.getTimezoneOffset();return new Date(x.getTime()-off*60000).toISOString().slice(0,16)};
async function v25Load(){
 const [a,f,e]=await Promise.all([lwsSupabase.from('appointments').select('*').order('appointment_at',{ascending:true}),lwsSupabase.from('client_files').select('*').order('created_at',{ascending:false}),lwsSupabase.from('employees').select('*').order('created_at')]);
 if(a.error)throw a.error;if(f.error)throw f.error;if(e.error)throw e.error;
 v25Appointments=a.data||[];v25Files=f.data||[];v25Team=e.data||[];
 v251PaintCalendar();v25PaintAppointments();v25PaintTeam();v25EnhanceCards();v25EnhanceDashboard();
}
function statusLabel(s){return v251t(s)||s}
function v25PaintAppointments(){
 const el=document.getElementById('v25-appointments');if(!el)return;
 const sorted=[...v25Appointments].sort((a,b)=>new Date(a.appointment_at)-new Date(b.appointment_at));
 el.innerHTML=sorted.length?sorted.map(a=>`<article class="v251-appt ${a.status}"><div><b>${esc(a.title)}</b><span>${new Date(a.appointment_at).toLocaleString()}</span></div><div><small>${esc(a.channel)}${a.location?' · '+esc(a.location):''} · ${esc(a.owner_name)}</small><p>${esc(a.note||'')}</p></div><select data-v25-appt-status="${a.id}"><option value="scheduled" ${a.status==='scheduled'?'selected':''}>${v251t('scheduled')}</option><option value="completed" ${a.status==='completed'?'selected':''}>${v251t('completed')}</option><option value="cancelled" ${a.status==='cancelled'?'selected':''}>${v251t('cancelled')}</option></select><div class="v251-row-actions"><button class="text-btn" data-v251-edit="${a.id}">${v251t('edit')}</button><button class="text-btn danger" data-v25-appt-delete="${a.id}">×</button></div></article>`).join(''):`<p class="empty-admin">${v251t('noAppointments')}</p>`;
}
function v251PaintCalendar(){
 const el=document.getElementById('v251-calendar'),label=document.getElementById('v251-month-label');if(!el)return;
 const locale=(window.lang==='th'?'th-TH':window.lang==='en'?'en-US':'lo-LA');label.textContent=v251Month.toLocaleDateString(locale,{month:'long',year:'numeric'});
 const y=v251Month.getFullYear(),m=v251Month.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();
 const heads=['sun','mon','tue','wed','thu','fri','sat'].map(k=>`<div class="v251-weekday">${v251t(k)}</div>`).join('');let cells='';
 for(let i=0;i<first;i++)cells+='<div class="v251-day muted"></div>';
 const today=new Date();
 for(let d=1;d<=days;d++){const date=new Date(y,m,d),key=[y,String(m+1).padStart(2,'0'),String(d).padStart(2,'0')].join('-');const items=v25Appointments.filter(a=>localInputValue(a.appointment_at).slice(0,10)===key);const isToday=date.toDateString()===today.toDateString();cells+=`<button class="v251-day ${isToday?'today':''}" type="button" data-v251-day="${key}"><span>${d}</span>${items.slice(0,3).map(a=>`<small class="${a.status}">${esc(a.title)}</small>`).join('')}${items.length>3?`<em>+${items.length-3}</em>`:''}</button>`}
 el.innerHTML=heads+cells;
}
function v25PaintTeam(){const el=document.getElementById('v25-team');if(!el)return;el.innerHTML=v25Team.map(e=>`<article><div><b>${esc(e.name)}</b><span>${esc(e.email||'')}</span></div><span class="status-pill status-contacted">${esc(e.role)}</span>${e.role!=='owner'?`<button class="text-btn danger" data-v25-employee-delete="${e.id}">×</button>`:''}</article>`).join('');}
function v25EnhanceDashboard(){const dash=document.getElementById('v24-dashboard');if(!dash)return;dash.querySelector('[data-v25-upcoming]')?.remove();const upcoming=v25Appointments.filter(a=>a.status==='scheduled'&&new Date(a.appointment_at)>=new Date()).length;dash.insertAdjacentHTML('beforeend',`<div data-v25-upcoming><span>${v251t('upcoming')}</span><b>${upcoming}</b></div>`);}
function v25EnhanceCards(){document.querySelectorAll('.lead-item').forEach(card=>{if(card.querySelector('.v25-files'))return;const id=String(card.dataset.id);const files=v25Files.filter(f=>String(f.lead_id)===id);const box=document.createElement('div');box.className='v25-files';box.innerHTML=`<div><b>${v251t('files')}</b><span>${files.length}</span></div><div class="v25-file-list">${files.map(f=>`<button class="text-btn" data-v25-download="${f.id}">${esc(f.file_name)}</button>`).join('')||'—'}</div><label class="btn btn-secondary small">${v251t('upload')}<input type="file" hidden data-v25-file="${id}"></label>`;card.appendChild(box);});}
function v251Open(appt=null,presetDate=''){
 const modal=document.getElementById('v251-modal'),leads=window.cachedLeads||[];document.getElementById('v251-id').value=appt?.id||'';document.getElementById('v251-title').value=appt?.title||'';document.getElementById('v251-date').value=appt?localInputValue(appt.appointment_at):(presetDate?`${presetDate}T09:00`:localInputValue(Date.now()+864e5));document.getElementById('v251-channel').value=appt?.channel||'whatsapp';document.getElementById('v251-location').value=appt?.location||'';document.getElementById('v251-note').value=appt?.note||'';
 const select=document.getElementById('v251-lead');select.innerHTML='<option value="">—</option>'+leads.map(l=>`<option value="${esc(l.id)}">${esc(l.name||l.full_name||'')} ${l.business_name?'— '+esc(l.business_name):''}</option>`).join('');select.value=appt?.lead_id||'';
 document.getElementById('v251-modal-title').textContent=appt?v251t('editTitle'):v251t('modalTitle');document.querySelectorAll('[data-v251-label]').forEach(x=>x.textContent=v251t(x.dataset.v251Label));modal.hidden=false;document.body.classList.add('modal-open');setTimeout(()=>document.getElementById('v251-title').focus(),20);
}
function v251Close(){document.getElementById('v251-modal').hidden=true;document.body.classList.remove('modal-open')}
async function v251Save(e){e.preventDefault();const id=document.getElementById('v251-id').value;const payload={title:document.getElementById('v251-title').value.trim(),lead_id:document.getElementById('v251-lead').value||null,appointment_at:new Date(document.getElementById('v251-date').value).toISOString(),channel:document.getElementById('v251-channel').value,location:document.getElementById('v251-location').value.trim()||null,note:document.getElementById('v251-note').value.trim()||null,owner_name:'Nutthaphon',updated_at:new Date().toISOString()};const q=id?lwsSupabase.from('appointments').update(payload).eq('id',id):lwsSupabase.from('appointments').insert(payload);const {error}=await q;if(error)throw error;v251Close();await v25Load();show(v251t('saved'));}
async function v25Upload(input){const file=input.files?.[0];if(!file)return;const leadId=input.dataset.v25File;const path=`${leadId}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await lwsSupabase.storage.from('client-files').upload(path,file);if(up.error)throw up.error;const {error}=await lwsSupabase.from('client_files').insert({lead_id:String(leadId),file_name:file.name,file_path:path,file_type:file.type,file_size:file.size});if(error)throw error;await v25Load();show('File uploaded ✓');}
async function v25Download(id){const f=v25Files.find(x=>x.id===id);if(!f)return;const {data,error}=await lwsSupabase.storage.from('client-files').createSignedUrl(f.file_path,60);if(error)throw error;window.open(data.signedUrl,'_blank');}
document.getElementById('v25-add-appointment')?.addEventListener('click',()=>v251Open());document.getElementById('v251-form')?.addEventListener('submit',e=>v251Save(e).catch(err=>show(err.message,'error')));document.querySelectorAll('[data-v251-close]').forEach(x=>x.addEventListener('click',v251Close));document.getElementById('v251-prev-month')?.addEventListener('click',()=>{v251Month=new Date(v251Month.getFullYear(),v251Month.getMonth()-1,1);v251PaintCalendar()});document.getElementById('v251-next-month')?.addEventListener('click',()=>{v251Month=new Date(v251Month.getFullYear(),v251Month.getMonth()+1,1);v251PaintCalendar()});
document.getElementById('v25-team-form')?.addEventListener('submit',async e=>{e.preventDefault();const payload={name:document.getElementById('v25-team-name').value.trim(),email:document.getElementById('v25-team-email').value.trim()||null,role:document.getElementById('v25-team-role').value};const {error}=await lwsSupabase.from('employees').insert(payload);if(error)return show(error.message,'error');e.target.reset();await v25Load();});
document.addEventListener('change',async e=>{try{if(e.target.dataset.v25File)await v25Upload(e.target);const id=e.target.dataset.v25ApptStatus;if(id){const {error}=await lwsSupabase.from('appointments').update({status:e.target.value,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error;await v25Load();}}catch(err){show(err.message,'error')}});
document.addEventListener('click',async e=>{try{const day=e.target.closest('[data-v251-day]');if(day){v251Open(null,day.dataset.v251Day);return}const edit=e.target.dataset.v251Edit;if(edit){v251Open(v25Appointments.find(a=>a.id===edit));return}const d=e.target.dataset.v25Download;if(d)await v25Download(d);const a=e.target.dataset.v25ApptDelete;if(a){if(confirm('Delete appointment?')){const {error}=await lwsSupabase.from('appointments').delete().eq('id',a);if(error)throw error;await v25Load();}}const emp=e.target.dataset.v25EmployeeDelete;if(emp){const {error}=await lwsSupabase.from('employees').delete().eq('id',emp);if(error)throw error;await v25Load();}}catch(err){show(err.message,'error')}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.getElementById('v251-modal')?.hidden)v251Close()});
const v25Observer=new MutationObserver(()=>v25EnhanceCards());window.addEventListener('load',()=>setTimeout(async()=>{try{document.getElementById('v25-appointments-title').textContent=v251t('appointments');document.getElementById('v25-add-appointment').textContent=v251t('addAppointment');document.getElementById('v25-team-title').textContent=v251t('team');await v25Load();v25Observer.observe(document.getElementById('lead-list'),{childList:true});}catch(e){console.warn('V2.5.1 migration required:',e.message)}},900));
