-- =====================================================================
-- LAO WEB STUDIO V2.9.0 — COMPLETE SUPABASE SETUP
-- One installation file for the complete website and CRM.
--
-- SAFE MODE:
--   • Creates missing tables, columns, functions, triggers and buckets.
--   • Keeps existing business records.
--   • Replaces conflicting RLS policies with one consistent policy set.
--
-- Run this complete file once in:
-- Supabase Dashboard → SQL Editor → New query → Run
-- =====================================================================

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------
-- SHARED UPDATED-AT TRIGGER
-- ---------------------------------------------------------------------
create or replace function public.lws_set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------
-- CORE PUBLIC WEBSITE TABLES
-- ---------------------------------------------------------------------
create table if not exists public.projects (
  id text primary key,
  category jsonb not null default '{}'::jsonb,
  name jsonb not null default '{}'::jsonb,
  description jsonb not null default '{}'::jsonb,
  url text not null default '',
  image_url text not null default 'assets/portfolio.jpg',
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.pricing (
  package text primary key,
  price text not null default '0',
  currency text not null default 'ກີບ',
  updated_at timestamptz not null default now()
);

-- bigint is intentionally used for a fresh installation because the
-- user's existing database uses bigint. Existing UUID tables are kept.
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  email text,
  business_name text,
  service text default 'website',
  budget text,
  message text,
  preferred_contact text default 'whatsapp',
  language text default 'lo',
  status text default 'new',
  source text default 'website',
  owner_id uuid,
  priority text default 'medium',
  next_follow_up date,
  admin_note text,
  lead_code text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Compatibility columns for databases created by older releases.
alter table public.leads
  add column if not exists name text,
  add column if not exists phone text,
  add column if not exists email text,
  add column if not exists business_name text,
  add column if not exists service text default 'website',
  add column if not exists budget text,
  add column if not exists message text,
  add column if not exists preferred_contact text default 'whatsapp',
  add column if not exists language text default 'lo',
  add column if not exists status text default 'new',
  add column if not exists source text default 'website',
  add column if not exists owner_id uuid,
  add column if not exists priority text default 'medium',
  add column if not exists next_follow_up date,
  add column if not exists admin_note text,
  add column if not exists lead_code text,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

-- Copy old full_name values into name when an old schema is detected.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='leads'
      and column_name='full_name'
  ) then
    execute 'update public.leads set name=full_name where name is null';
  end if;
end $$;

create index if not exists leads_status_idx
  on public.leads(status);
create index if not exists leads_created_at_idx
  on public.leads(created_at desc);

-- ---------------------------------------------------------------------
-- CRM TABLES
-- ---------------------------------------------------------------------
create table if not exists public.employees (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text,
  phone text,
  role text not null default 'staff',
  active boolean not null default true,
  auth_user_id uuid,
  job_title text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quotations (
  id uuid primary key default gen_random_uuid(),
  quote_no text unique not null,
  lead_id text,
  customer_name text not null,
  customer_email text,
  service text,
  amount numeric(14,2) not null default 0,
  currency text not null default 'ກີບ',
  valid_until date,
  status text not null default 'draft',
  created_by text not null default 'Nutthaphon',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.appointments (
  id uuid primary key default gen_random_uuid(),
  lead_id text,
  title text not null,
  appointment_at timestamptz not null,
  channel text not null default 'whatsapp',
  location text,
  note text,
  owner_name text default 'Nutthaphon',
  status text not null default 'scheduled',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.client_files (
  id uuid primary key default gen_random_uuid(),
  lead_id text,
  file_name text not null,
  file_path text not null,
  file_type text,
  file_size bigint,
  uploaded_by text default 'Nutthaphon',
  created_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  lead_id text,
  project_name text,
  assigned_employee_id uuid,
  assigned_to text default 'Nutthaphon',
  customer_user_id uuid references auth.users(id) on delete set null,
  status text not null default 'todo',
  priority text not null default 'medium',
  progress integer not null default 0,
  sort_order integer not null default 0,
  due_date date,
  created_by text default 'Nutthaphon',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  action text not null,
  entity_type text,
  entity_id text,
  detail text,
  actor_name text default 'Nutthaphon',
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  message text,
  type text not null default 'info',
  related_type text,
  related_id text,
  recipient_employee_id uuid,
  recipient_name text default 'Nutthaphon',
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.company_settings (
  id integer primary key default 1,
  company_name text not null default 'Lao Web Studio',
  phone text default '02052811825',
  whatsapp text default '02052811825',
  email text default 'info@laowebstudio.com',
  domain text default 'laowebstudio.com',
  facebook text default 'Lao Web Studio',
  address_lo text default
    'ນະຄອນຫຼວງວຽງຈັນ, ເມືອງໄຊທານີ, ບ້ານຕານມີໄຊ',
  google_maps_url text,
  logo_url text,
  currency text default 'ກີບ',
  updated_at timestamptz not null default now()
);

create table if not exists public.services (
  id uuid primary key default gen_random_uuid(),
  name_lo text not null,
  name_th text,
  name_en text,
  description_lo text,
  description_th text,
  description_en text,
  base_price numeric(14,2) default 0,
  currency text default 'ກີບ',
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.roles_permissions (
  id uuid primary key default gen_random_uuid(),
  role text not null unique,
  dashboard boolean not null default true,
  leads boolean not null default false,
  calendar boolean not null default false,
  quotations boolean not null default false,
  files boolean not null default false,
  tasks boolean not null default false,
  projects boolean not null default false,
  pricing boolean not null default false,
  services boolean not null default false,
  team boolean not null default false,
  settings boolean not null default false,
  notifications boolean not null default true,
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- AUTHENTICATION / CUSTOMER PORTAL TABLES
-- ---------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  email text,
  role text not null default 'customer',
  lead_id text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.invoices (
  id uuid primary key default gen_random_uuid(),
  invoice_number text not null unique,
  lead_id text,
  customer_user_id uuid references auth.users(id) on delete set null,
  customer_name text not null,
  customer_email text,
  project_name text,
  description text,
  subtotal numeric(14,2) not null default 0,
  discount numeric(14,2) not null default 0,
  tax numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  currency text not null default 'ກີບ',
  status text not null default 'draft',
  issue_date date not null default current_date,
  due_date date,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null
    references public.invoices(id) on delete cascade,
  amount numeric(14,2) not null,
  currency text not null default 'ກີບ',
  payment_method text default 'bank_transfer',
  payment_date date not null default current_date,
  reference text,
  note text,
  recorded_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.project_updates (
  id uuid primary key default gen_random_uuid(),
  lead_id text,
  customer_user_id uuid references auth.users(id) on delete cascade,
  project_name text not null,
  title text not null,
  message text,
  progress integer not null default 0,
  status text not null default 'in_progress',
  is_visible_to_customer boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- DEFAULT DATA
-- ---------------------------------------------------------------------
insert into public.company_settings(id)
values (1)
on conflict (id) do nothing;

insert into public.employees(name, role)
select 'Nutthaphon', 'owner'
where not exists (
  select 1 from public.employees
  where lower(name)='nutthaphon'
);

insert into public.roles_permissions
(role,dashboard,leads,calendar,quotations,files,tasks,projects,
 pricing,services,team,settings,notifications)
values
('owner',true,true,true,true,true,true,true,true,true,true,true,true),
('manager',true,true,true,true,true,true,true,true,true,true,false,true),
('staff',true,true,true,false,true,true,false,false,false,false,false,true)
on conflict (role) do update set
  dashboard=excluded.dashboard,
  leads=excluded.leads,
  calendar=excluded.calendar,
  quotations=excluded.quotations,
  files=excluded.files,
  tasks=excluded.tasks,
  projects=excluded.projects,
  pricing=excluded.pricing,
  services=excluded.services,
  team=excluded.team,
  settings=excluded.settings,
  notifications=excluded.notifications,
  updated_at=now();

insert into public.pricing(package,price,currency)
values
  ('starter','200.000','ກີບ'),
  ('business','500.000','ກີບ'),
  ('premium','800.000','ກີບ')
on conflict (package) do nothing;

insert into public.projects
(id,category,name,description,url,image_url,sort_order)
values (
  'tum-pa-guay',
  '{"lo":"ເວັບໄຊຕ໌ຮ້ານອາຫານ","th":"เว็บไซต์ร้านอาหาร","en":"Restaurant Website"}',
  '{"lo":"ຮ້ານຕຳຕູບປ່າກ້ວຍ","th":"ร้านตำตูบป่าก้วย","en":"Tum Pa Guay Restaurant"}',
  '{"lo":"ເວັບໄຊຕ໌ຮ້ານອາຫານ ພ້ອມເມນູ ແຜນທີ່ ແລະ ປຸ່ມຕິດຕໍ່","th":"เว็บไซต์ร้านอาหาร พร้อมเมนู แผนที่ และปุ่มติดต่อ","en":"Restaurant website with menu, map and contact actions."}',
  'https://nutthaphon5599.github.io/tum-pa-guay-restaurant-6.2/',
  'assets/portfolio.jpg',
  0
)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------
-- AUTH PROFILE AUTOMATION AND OWNER BACKFILL
-- ---------------------------------------------------------------------
create or replace function public.lws_handle_new_user()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  insert into public.profiles(id,full_name,email,role)
  values(
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name',''),
    new.email,
    case
      when not exists (
        select 1 from public.profiles where role='owner'
      ) then 'owner'
      else coalesce(new.raw_user_meta_data->>'role','customer')
    end
  )
  on conflict (id) do update set
    email=excluded.email,
    updated_at=now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.lws_handle_new_user();

-- Backfill users created before this setup. The oldest account becomes
-- owner only when no owner profile currently exists.
insert into public.profiles(id,full_name,email,role)
select
  u.id,
  coalesce(u.raw_user_meta_data->>'full_name',''),
  u.email,
  case
    when row_number() over(order by u.created_at)=1
      and not exists(select 1 from public.profiles where role='owner')
    then 'owner'
    else 'customer'
  end
from auth.users u
on conflict (id) do update set
  email=excluded.email,
  updated_at=now();

-- ---------------------------------------------------------------------
-- ROLE HELPERS
-- ---------------------------------------------------------------------
create or replace function public.current_role()
returns text
language sql
stable
security definer
set search_path=public
as $$
  select coalesce(
    (
      select role from public.profiles
      where id=auth.uid() and is_active=true
    ),
    'customer'
  );
$$;

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select public.current_role() in ('owner','manager','staff');
$$;

-- ---------------------------------------------------------------------
-- PUBLIC LEAD RPC — THE ONLY PUBLIC WRITE PATH
-- Compatible with bigint or UUID leads.id because ID is returned as text.
-- ---------------------------------------------------------------------
drop function if exists public.submit_public_lead(
  text,text,text,text,text,text,text,text,text
);

create function public.submit_public_lead(
  p_name text,
  p_phone text,
  p_email text default null,
  p_business_name text default null,
  p_service text default 'website',
  p_budget text default null,
  p_message text default '',
  p_preferred_contact text default 'whatsapp',
  p_language text default 'lo'
)
returns text
language plpgsql
security definer
set search_path=public
as $$
declare
  v_id text;
begin
  if nullif(btrim(p_name),'') is null then
    raise exception 'name_required';
  end if;
  if nullif(btrim(p_phone),'') is null then
    raise exception 'phone_required';
  end if;
  if nullif(btrim(p_message),'') is null then
    raise exception 'message_required';
  end if;

  insert into public.leads(
    name,phone,email,business_name,service,budget,message,
    preferred_contact,language,status,source,created_at,updated_at
  )
  values(
    left(btrim(p_name),200),
    left(btrim(p_phone),80),
    nullif(left(btrim(coalesce(p_email,'')),320),''),
    nullif(left(btrim(coalesce(p_business_name,'')),250),''),
    left(coalesce(nullif(btrim(p_service),''),'website'),100),
    nullif(left(btrim(coalesce(p_budget,'')),100),''),
    left(btrim(p_message),5000),
    left(coalesce(nullif(btrim(p_preferred_contact),''),'whatsapp'),50),
    case when p_language in ('lo','th','en') then p_language else 'lo' end,
    'new',
    'website',
    now(),
    now()
  )
  returning id::text into v_id;

  return v_id;
end;
$$;

revoke all on function public.submit_public_lead(
  text,text,text,text,text,text,text,text,text
) from public;
grant execute on function public.submit_public_lead(
  text,text,text,text,text,text,text,text,text
) to anon,authenticated;

-- Public health check used by system-check.html.
create or replace function public.lws_public_health_check()
returns jsonb
language sql
stable
security definer
set search_path=public
as $$
  select jsonb_build_object(
    'ok',true,
    'version','2.9.0',
    'project_ref',current_database(),
    'lead_rpc',to_regprocedure(
      'public.submit_public_lead(text,text,text,text,text,text,text,text,text)'
    ) is not null,
    'checked_at',now()
  );
$$;

revoke all on function public.lws_public_health_check() from public;
grant execute on function public.lws_public_health_check()
to anon,authenticated;

-- ---------------------------------------------------------------------
-- UPDATED-AT TRIGGERS
-- ---------------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array[
    'projects','pricing','leads','employees','quotations',
    'appointments','tasks','company_settings','services',
    'roles_permissions','profiles','invoices'
  ]
  loop
    execute format(
      'drop trigger if exists %I on public.%I',
      t || '_updated_at', t
    );
    execute format(
      'create trigger %I before update on public.%I
       for each row execute function public.lws_set_updated_at()',
      t || '_updated_at', t
    );
  end loop;
end $$;

-- ---------------------------------------------------------------------
-- PAYMENT STATUS AUTOMATION
-- ---------------------------------------------------------------------
create or replace function public.lws_refresh_invoice_status(
  p_invoice_id uuid
)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  v_paid numeric(14,2);
  v_total numeric(14,2);
begin
  select total into v_total
  from public.invoices where id=p_invoice_id;

  select coalesce(sum(amount),0) into v_paid
  from public.payments where invoice_id=p_invoice_id;

  update public.invoices
  set status=case
    when v_total > 0 and v_paid >= v_total then 'paid'
    when v_paid > 0 then 'partially_paid'
    when due_date < current_date
      and status not in ('paid','cancelled') then 'overdue'
    else status
  end,
  updated_at=now()
  where id=p_invoice_id;
end;
$$;

create or replace function public.lws_payment_status_trigger()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  perform public.lws_refresh_invoice_status(
    coalesce(new.invoice_id,old.invoice_id)
  );
  return coalesce(new,old);
end;
$$;

drop trigger if exists payments_refresh_invoice
on public.payments;
create trigger payments_refresh_invoice
after insert or update or delete on public.payments
for each row execute function public.lws_payment_status_trigger();

-- ---------------------------------------------------------------------
-- ROW LEVEL SECURITY
-- ---------------------------------------------------------------------
do $$
declare
  t text;
  p record;
begin
  foreach t in array array[
    'projects','pricing','leads','employees','quotations',
    'appointments','client_files','tasks','activities',
    'notifications','company_settings','services',
    'roles_permissions','profiles','invoices','payments',
    'project_updates'
  ]
  loop
    execute format(
      'alter table public.%I enable row level security', t
    );

    for p in
      select policyname from pg_policies
      where schemaname='public' and tablename=t
    loop
      execute format(
        'drop policy if exists %I on public.%I',
        p.policyname,t
      );
    end loop;
  end loop;
end $$;

-- Public website read policies.
create policy lws_public_projects_read
on public.projects for select to anon,authenticated
using(true);

create policy lws_public_pricing_read
on public.pricing for select to anon,authenticated
using(true);

create policy lws_public_services_read
on public.services for select to anon,authenticated
using(coalesce(is_active,true)=true or public.is_staff());

create policy lws_public_settings_read
on public.company_settings for select to anon,authenticated
using(true);

-- Staff CRUD.
create policy lws_staff_leads
on public.leads for all to authenticated
using(public.is_staff())
with check(public.is_staff());

create policy lws_staff_projects_write
on public.projects for all to authenticated
using(public.is_staff())
with check(public.is_staff());

create policy lws_staff_pricing_write
on public.pricing for all to authenticated
using(public.is_staff())
with check(public.is_staff());

create policy lws_staff_services_write
on public.services for all to authenticated
using(public.is_staff())
with check(public.is_staff());

create policy lws_staff_settings_write
on public.company_settings for all to authenticated
using(public.is_staff())
with check(public.is_staff());

create policy lws_staff_employees
on public.employees for all to authenticated
using(public.is_staff())
with check(public.current_role() in ('owner','manager'));

create policy lws_staff_quotations
on public.quotations for all to authenticated
using(public.is_staff())
with check(public.is_staff());

create policy lws_staff_appointments
on public.appointments for all to authenticated
using(public.is_staff())
with check(public.is_staff());

create policy lws_staff_client_files
on public.client_files for all to authenticated
using(public.is_staff())
with check(public.is_staff());

create policy lws_staff_activities
on public.activities for all to authenticated
using(public.is_staff())
with check(public.is_staff());

create policy lws_staff_notifications
on public.notifications for all to authenticated
using(public.is_staff())
with check(public.is_staff());

create policy lws_staff_roles_read
on public.roles_permissions for select to authenticated
using(public.is_staff());

create policy lws_management_roles_write
on public.roles_permissions for all to authenticated
using(public.current_role() in ('owner','manager'))
with check(public.current_role() in ('owner','manager'));

-- Profiles.
create policy lws_profiles_read
on public.profiles for select to authenticated
using(id=auth.uid() or public.is_staff());

create policy lws_profiles_management
on public.profiles for all to authenticated
using(public.current_role() in ('owner','manager'))
with check(public.current_role() in ('owner','manager'));

-- Staff and customer-linked portal records.
create policy lws_tasks_read
on public.tasks for select to authenticated
using(public.is_staff() or customer_user_id=auth.uid());

create policy lws_tasks_staff_write
on public.tasks for all to authenticated
using(public.is_staff())
with check(public.is_staff());

create policy lws_invoices_read
on public.invoices for select to authenticated
using(public.is_staff() or customer_user_id=auth.uid());

create policy lws_invoices_staff_write
on public.invoices for all to authenticated
using(public.is_staff())
with check(public.is_staff());

create policy lws_payments_read
on public.payments for select to authenticated
using(
  public.is_staff()
  or exists(
    select 1 from public.invoices i
    where i.id=payments.invoice_id
      and i.customer_user_id=auth.uid()
  )
);

create policy lws_payments_staff_write
on public.payments for all to authenticated
using(public.is_staff())
with check(public.is_staff());

create policy lws_updates_read
on public.project_updates for select to authenticated
using(
  public.is_staff()
  or (
    customer_user_id=auth.uid()
    and is_visible_to_customer=true
  )
);

create policy lws_updates_staff_write
on public.project_updates for all to authenticated
using(public.is_staff())
with check(public.is_staff());

-- ---------------------------------------------------------------------
-- STORAGE
-- ---------------------------------------------------------------------
insert into storage.buckets(id,name,public)
values
  ('portfolio','portfolio',true),
  ('client-files','client-files',false)
on conflict(id) do update set
  public=excluded.public;

-- Remove only Lao Web Studio policies by their exact names.
drop policy if exists lws_portfolio_public_read
on storage.objects;
drop policy if exists lws_portfolio_staff_insert
on storage.objects;
drop policy if exists lws_portfolio_staff_update
on storage.objects;
drop policy if exists lws_portfolio_staff_delete
on storage.objects;
drop policy if exists lws_client_files_staff
on storage.objects;

create policy lws_portfolio_public_read
on storage.objects for select to anon,authenticated
using(bucket_id='portfolio');

create policy lws_portfolio_staff_insert
on storage.objects for insert to authenticated
with check(
  bucket_id='portfolio' and public.is_staff()
);

create policy lws_portfolio_staff_update
on storage.objects for update to authenticated
using(bucket_id='portfolio' and public.is_staff())
with check(bucket_id='portfolio' and public.is_staff());

create policy lws_portfolio_staff_delete
on storage.objects for delete to authenticated
using(bucket_id='portfolio' and public.is_staff());

create policy lws_client_files_staff
on storage.objects for all to authenticated
using(bucket_id='client-files' and public.is_staff())
with check(bucket_id='client-files' and public.is_staff());

-- ---------------------------------------------------------------------
-- REALTIME
-- ---------------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array[
    'tasks','notifications','invoices','payments',
    'project_updates'
  ]
  loop
    begin
      execute format(
        'alter publication supabase_realtime
         add table public.%I',t
      );
    exception when duplicate_object then
      null;
    end;
  end loop;
end $$;

-- Force PostgREST to discover all new schema objects.
notify pgrst,'reload schema';

-- ---------------------------------------------------------------------
-- FINAL VERIFICATION
-- ---------------------------------------------------------------------
select jsonb_build_object(
  'result','Lao Web Studio complete setup installed',
  'version','2.9.0',
  'lead_id_type',(
    select data_type
    from information_schema.columns
    where table_schema='public'
      and table_name='leads'
      and column_name='id'
  ),
  'rpc_ready',
    to_regprocedure(
      'public.submit_public_lead(text,text,text,text,text,text,text,text,text)'
    ) is not null,
  'health_check_ready',
    to_regprocedure('public.lws_public_health_check()') is not null,
  'tables_ready',(
    select count(*)
    from information_schema.tables
    where table_schema='public'
      and table_name in (
        'projects','pricing','leads','employees','quotations',
        'appointments','client_files','tasks','activities',
        'notifications','company_settings','services',
        'roles_permissions','profiles','invoices','payments',
        'project_updates'
      )
  ),
  'installed_at',now()
) as installation_result;
