
-- Lao Web Studio V2.6.1 Enterprise
-- Safe migration: adds new tables without deleting existing data.

create extension if not exists pgcrypto;

create table if not exists public.tasks (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  lead_id text,
  project_name text,
  assigned_employee_id uuid,
  assigned_to text default 'Nutthaphon',
  status text not null default 'todo'
    check (status in ('todo','in_progress','review','completed','cancelled')),
  priority text not null default 'medium'
    check (priority in ('low','medium','high','urgent')),
  progress integer not null default 0 check (progress between 0 and 100),
  due_date date,
  created_by text default 'Nutthaphon',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  action text not null,
  entity_type text,
  entity_id text,
  detail text,
  actor_name text default 'Nutthaphon',
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  message text,
  type text not null default 'info'
    check (type in ('info','success','warning','danger')),
  related_type text,
  related_id text,
  recipient_employee_id uuid,
  recipient_name text default 'Nutthaphon',
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.company_settings (
  id integer primary key default 1 check (id = 1),
  company_name text not null default 'Lao Web Studio',
  phone text default '02052811825',
  whatsapp text default '02052811825',
  email text default 'info@laowebstudio.com',
  domain text default 'laowebstudio.com',
  facebook text default 'Lao Web Studio',
  address_lo text default 'ນະຄອນຫຼວງວຽງຈັນ, ເມືອງໄຊທານີ, ບ້ານຕານມີໄຊ',
  google_maps_url text,
  logo_url text,
  currency text default 'ກີບ',
  updated_at timestamptz not null default now()
);
insert into public.company_settings(id) values (1) on conflict (id) do nothing;

create table if not exists public.services (
  id uuid primary key default gen_random_uuid(),
  name_lo text not null,
  name_th text,
  name_en text,
  description_lo text,
  description_th text,
  description_en text,
  base_price numeric(14,2) default 0,
  currency text default 'ກີບ',
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.roles_permissions (
  id uuid primary key default gen_random_uuid(),
  role text not null unique,
  dashboard boolean not null default true,
  leads boolean not null default false,
  calendar boolean not null default false,
  quotations boolean not null default false,
  files boolean not null default false,
  tasks boolean not null default false,
  projects boolean not null default false,
  pricing boolean not null default false,
  services boolean not null default false,
  team boolean not null default false,
  settings boolean not null default false,
  notifications boolean not null default true,
  updated_at timestamptz not null default now()
);

insert into public.roles_permissions
(role,dashboard,leads,calendar,quotations,files,tasks,projects,pricing,services,team,settings,notifications)
values
('owner',   true,true,true,true,true,true,true,true,true,true,true,true),
('manager', true,true,true,true,true,true,true,true,true,true,false,true),
('staff',   true,true,true,false,true,true,false,false,false,false,false,true)
on conflict (role) do update set
  dashboard = excluded.dashboard,
  leads = excluded.leads,
  calendar = excluded.calendar,
  quotations = excluded.quotations,
  files = excluded.files,
  tasks = excluded.tasks,
  projects = excluded.projects,
  pricing = excluded.pricing,
  services = excluded.services,
  team = excluded.team,
  settings = excluded.settings,
  notifications = excluded.notifications,
  updated_at = now();

-- Ensure employees can link to authentication and be enabled/disabled.
alter table if exists public.employees
  add column if not exists auth_user_id uuid,
  add column if not exists is_active boolean not null default true;

create index if not exists idx_tasks_status on public.tasks(status);
create index if not exists idx_tasks_due_date on public.tasks(due_date);
create index if not exists idx_notifications_unread on public.notifications(is_read, created_at desc);
create index if not exists idx_activities_created_at on public.activities(created_at desc);
create index if not exists idx_services_active on public.services(is_active, sort_order);

-- Enable RLS. Policies below allow authenticated users.
alter table public.tasks enable row level security;
alter table public.activities enable row level security;
alter table public.notifications enable row level security;
alter table public.company_settings enable row level security;
alter table public.services enable row level security;
alter table public.roles_permissions enable row level security;

do $$
declare t text;
begin
  foreach t in array array['tasks','activities','notifications','company_settings','services','roles_permissions']
  loop
    execute format('drop policy if exists "authenticated_all_%s" on public.%I', t, t);
    execute format(
      'create policy "authenticated_all_%s" on public.%I for all to authenticated using (true) with check (true)',
      t, t
    );
  end loop;
end $$;

-- Seed services only when empty.
insert into public.services(name_lo,name_th,name_en,base_price,currency,sort_order)
select * from (values
 ('ເວັບໄຊບໍລິສັດ','เว็บไซต์บริษัท','Company Website',500000::numeric,'ກີບ',1),
 ('ເວັບໄຊຮ້ານອາຫານ','เว็บไซต์ร้านอาหาร','Restaurant Website',500000::numeric,'ກີບ',2),
 ('ເວັບໄຊໂຮງແຮມ','เว็บไซต์โรงแรม','Hotel Website',800000::numeric,'ກີບ',3),
 ('ຮ້ານຄ້າອອນລາຍ','ร้านค้าออนไลน์','E-commerce',1200000::numeric,'ກີບ',4),
 ('SEO ແລະ Google','SEO และ Google','SEO & Google',300000::numeric,'ກີບ',5),
 ('ບຳລຸງຮັກສາເວັບ','ดูแลเว็บไซต์','Website Maintenance',200000::numeric,'ກີບ',6)
) as seed(name_lo,name_th,name_en,base_price,currency,sort_order)
where not exists (select 1 from public.services);

-- Realtime support (safe when publication exists).
do $$
begin
  alter publication supabase_realtime add table public.notifications;
exception when duplicate_object then null;
end $$;
